replicaCount: 2
image:
  repository: quay.io/openshiftdemos/rollouts-demo
  tag: "93a1a64264f4d7f0d75aa011d8d3405fe4f95415"
  port: 8080
  pullPolicy: IfNotPresent
service:
  port: 8080
  previewPort: 8081
  targetPort: 8080
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20
smokeTest:
  enabled: false
revisionHistoryLimit: 2
commonAnnotations:
  team: carbon
  project: t3aPaC
