# values/values.common.yaml - Base configuration for all environments
replicaCount: 1
image:
  repository: ghcr.io/ihonwub/curly-spork
  tag: "888f023850df847c5d949f5cd4d88385017e1075" # Will be updated by CI
  port: 8080
  pullPolicy: IfNotPresent
service:
  port: 8080
  previewPort: 8081
  targetPort: 8080
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 6       # Fail only after 6 failures
  timeoutSeconds: 2         # Wait 2 seconds for each response
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6       # Fail only after 6 failures
  timeoutSeconds: 2         # Wait 2 seconds for each response
smokeTest:
  enabled: false
revisionHistoryLimit: 1

rollout:
  strategy:
    blueGreen:
      enabled: true  # Set to false for canary deployment
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      scaleDownDelaySeconds: 30
    canary:
      setWeight: 20
      setWeight2: 40
      setWeight3: 60
      setWeight4: 80
      pauseDuration: "30s"

smokeTest:
  enabled: true  # Only applies when blueGreen.enabled is true

# Common annotations applied to all environments
commonAnnotations:
  team: carbon
  project: t3aPaC
# Default resource limits (conservative)
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
# Default cluster domain (should be overridden per environment)
clusterDomain: ""
