apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollou-demo-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ihonwub/refactored-robot.git
    targetRevision: main
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
