---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "rolloutdemo.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app: {{ template "rolloutdemo.name" . }}
spec:
  to:
    kind: Service
    name: {{ template "rolloutdemo.fullname" . }}-{{ .Release.Namespace }}
  port:
    targetPort: http
  host: {{ include "rolloutdemo.activeRouteHost" . }}
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "rolloutdemo.fullname" . }}-preview-{{ .Release.Namespace }}
  labels:
    app: {{ template "rolloutdemo.name" . }}
spec:
  to:
    kind: Service
    name: {{ template "rolloutdemo.fullname" . }}-preview-{{ .Release.Namespace }}
  port:
    targetPort: http
  host: {{ include "rolloutdemo.previewRouteHost" . }}
  tls:
    termination: edge
