clusterDomain: apps.e3c5k7g5w3o7p7w.5vc5.p1.openshiftapps.com

replicaCount: 1

image:
  repository: quay.io/openshiftdemos/rollouts-demo
  tag: "blue"
  port: 8080
  pullPolicy: IfNotPresent

service:
  port: 8080
  previewPort: 8081
  targetPort: 8080

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

smokeTest:
  enabled: true

revisionHistoryLimit: 1
commonAnnotations:
  team: carbon
  project: t3aPaC
