# values/envs/dev.yaml - Development environment overrides
# clusterDomain: apps.e3c5k7g5w3o7p7w.5vc5.p1.openshiftapps.com

# Higher replica count for dev testing
replicaCount: 2
# Development-specific image settings
image:
  pullPolicy: Always # Always pull latest in dev
  repository: ghcr.io/ihonwub/curly-spork
  tag: "f1dce09c362d359963e273ae9196be6b3bb5a99d" # Will be updated by CI
# Keep more revision history for debugging
revisionHistoryLimit: 3
rollout:
  strategy:
    blueGreen:
      enabled: false # Use rolling update instead
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "50%"
smokeTest:
  enabled: false # No smoke tests for rolling update
# Higher resource limits for dev testing
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
# # Development-specific annotations
# commonAnnotations:
#   team: carbon
#   project: t3aPaC
#   environment: dev

# # Development-specific labels for pods
# podLabels:
#   environment: dev
#   tier: development
