# values/envs/dev.yaml - Development environment overrides
# clusterDomain: apps.e3c5k7g5w3o7p7w.5vc5.p1.openshiftapps.com

# Higher replica count for dev testing
replicaCount: 2

# Development-specific image settings
image:
  pullPolicy: Always  # Always pull latest in dev
  repository: ghcr.io/ihonwub/curly-spork
  tag: "93a1a64264f4d7f0d75aa011d8d3405fe4f95415" # Will be updated by CI

# Enable smoke tests in development
smokeTest:
  enabled: true

# Keep more revision history for debugging
revisionHistoryLimit: 3

# Development rollout strategy - manual promotion for testing
rollout:
  strategy:
    blueGreen:
      autoPromotionEnabled: false  # Manual promotion in dev
      autoPromotionSeconds: 60     # Longer wait time for manual testing
      scaleDownDelaySeconds: 600   # Keep old version longer for comparison

# Higher resource limits for dev testing
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# # Development-specific annotations
# commonAnnotations:
#   team: carbon
#   project: t3aPaC
#   environment: dev

# # Development-specific labels for pods
# podLabels:
#   environment: dev
#   tier: development