# values/envs/dev.yaml - Development environment overrides
# clusterDomain: apps.e3c5k7g5w3o7p7w.5vc5.p1.openshiftapps.com

# Higher replica count for dev testing
replicaCount: 2
# Development-specific image settings
image:
  pullPolicy: Always # Always pull latest in dev
  tag: "15c8e728ffd59b7256a2290b1e14277b6152b0bd" # Will be updated by CI
# Keep more revision history for debugging
revisionHistoryLimit: 3
rollout:
  strategy:
    blueGreen:
      enabled: false # Use rolling update instead
smokeTest:
  enabled: false # No smoke tests for rolling update
# Higher resource limits for dev testing
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
# # Development-specific annotations
# commonAnnotations:
#   team: carbon
#   project: t3aPaC
#   environment: dev
# # Development-specific labels for pods
# podLabels:
#   environment: dev
#   tier: development
