---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout-demo-environments
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            branch: env/dev
            namespace: rollout-dev
          - env: qa
            branch: env/qa
            namespace: rollout-qa
  template:
    metadata:
      name: rollout-{{.env}}
      labels:
        environment: {{.env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/ihonwub/refactored-robot.git
        targetRevision: {{.branch}}
        path: .  # Root of the branch where rendered manifests are stored
      destination:
        server: https://kubernetes.default.svc
        namespace: {{.namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true