apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout-demo-environments
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - env: dev
            branch: env/dev
            namespace: rollout-dev
            appName: rollout-dev
          - env: qa
            branch: env/qa  
            namespace: rollout-qa
            appName: rollout-qa
  template:
    metadata:
      name: '{{appName}}'
      labels:
        environment: '{{env}}'
        managed-by: applicationset
    spec:
      project: default
      source:
        repoURL: https://github.com/ihonwub/refactored-robot.git
        targetRevision: '{{branch}}'
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true


# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: rollout-demo-environments
#   namespace: openshift-gitops
# spec:
#   generators:
#     - list:
#         elements:
#           - env: dev
#             branch: env/dev
#             namespace: rollout-dev
#   template:
#     metadata:
#       name: 'rollout-{{env}}'
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/ihonwub/refactored-robot.git
#         targetRevision: '{{branch}}'
#         path: .
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: '{{namespace}}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         syncOptions:
#           - CreateNamespace=true