---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout-demo-environments
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            branch: main
          # - env: qa
          #   branch: env/qa
  template:
    metadata:
      name: rollout-{{.env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/ihonwub/refactored-robot.git
        targetRevision: main
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: {{.env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
